class ReferenceModel {
  int? id; // Removed 'required' since it's auto-generated by the database
  String title;
  String bookName;
  String bookPath;
  String navIndex;

  ReferenceModel({
    this.id, // Made 'id' nullable since it's auto-generated
    required this.title,
    required this.bookName,
    required this.bookPath,
    required this.navIndex,
  });

  Map<String, dynamic> toMap() {
    return {
      'id': id, // Include 'id' in the map, but it can be null when inserting
      'title': title,
      'bookName': bookName,
      'bookPath': bookPath,
      'navIndex': navIndex,
    };
  }
}
